import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const moveToCounter = () => router.push("/counter");
  const moveToTodoList = () => router.push("/todolist");

  return (
    <div className={styles.container}>
      <Head>
        <title>Austin Power</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Austin Power</a>
        </h1>

        <div>
          <button className={styles.button} onClick={moveToCounter}>
            카운터
          </button>
          <button className={styles.button} onClick={moveToTodoList}>
            투두 리스트
          </button>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
